version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=agri_project.settings_production
      - DEBUG=False
      - SECRET_KEY=django-insecure-guw!01n280=siz6+^9ji%d)hu693sxv2uu!#7=4yd=6nrj1t2p
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
    volumes:
      - ./media:/app/media
      - ./db.sqlite3:/app/db.sqlite3
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "--workers", "3", "agri_project.wsgi:application"]
