# Generated by Django 5.2.5 on 2025-09-02 17:13

import analyze.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysisresult',
            options={'ordering': ['-created_at'], 'verbose_name': 'Analysis result', 'verbose_name_plural': 'Analysis results'},
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='result',
            field=models.CharField(choices=[('Badly_damaged', 'Badly_damaged'), ('Dead', 'Dead'), ('Infected', 'Infected'), ('Non_infected', 'Non_infected')], max_length=64, verbose_name='Result'),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='rgb_image',
            field=models.ImageField(blank=True, help_text='First RGB image associated with this session.', null=True, upload_to=analyze.models.UploadToPath('rgb'), verbose_name='RGB image'),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='session_id',
            field=models.CharField(db_index=True, max_length=128, verbose_name='Session ID'),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='thermal_image',
            field=models.ImageField(blank=True, help_text='First Thermal image associated with this session.', null=True, upload_to=analyze.models.UploadToPath('thermal'), verbose_name='Thermal image'),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who triggered the analysis (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_results', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='analysisresult',
            index=models.Index(fields=['session_id'], name='analyze_ana_session_754b02_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisresult',
            index=models.Index(fields=['session_id', '-created_at'], name='analyze_ana_session_b5a0f8_idx'),
        ),
    ]
